version: '2'
services:
  aria2-local:
    user: '501:20'
    container_name: aria2
    image: xiaozhuai/aria2
    ports:
      - 6800:6800
    volumes:
      - /tmp/aria2-local/config:/config
      - /tmp/aria2-local/downloads:/downloads
